version: "3.4"

services:
  mongodb:
    container_name: "mongodb"
    image: mongo
    ports:
      - "27017:27017"
    command: mongod --port 27017
    restart: always
    networks:
      - adventourous

networks:
  adventourous:
    external: true
